# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8e52d4011d91600b11c64e43693a8192b06995bc2c5c6c2c1372eaf52498d33cefeb5f7c98d6bf222035385afcfc6c23ccbd6c80748adf07ccd802b2e8fa1983

test:
  secret_key_base: 7b7e903e4fc460f1529d6bbdfa99189ef0ac67e0f9b97f907d63149cc85f8bd75213ea54fa8fea45770c50b540b7d3b9913769557c0a8397a0e0e7aa10540948

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
